### ISSUE TITLE
RenameToolkitFiles.bat does not rename the Adapter folder

### ISSUE THREAD

**Issue by michaelhoehn** [BHoM/template-repository#15] opened 2022-12-01 14:45 UTC
#### Description:

After using the .bat to batch rename I found the following folder structure.

![image](https://user-images.githubusercontent.com/54593392/205081938-0e000d39-2baf-436a-8de8-18d7ec3c6265.png)

The structure within the solution was correctly named.

![image](https://user-images.githubusercontent.com/54593392/205082054-c18659d2-483d-4a7c-a412-496eba1d731e.png)

#### Steps to reproduce:

Make a new repo using the template repo, and use the .bat to rename.

#### Expected behaviour:

All folders should be renamed according to the .bat input from the user.

**Comment by alelom** [comment] 2022-12-01 16:33
@michaelhoehn are the files inside `SoftwareName_Adapter` renamed to the right name or not?

**Comment by alelom** [comment] 2022-12-01 16:43
I can't reproduce on my end:

![image](https://user-images.githubusercontent.com/6352844/205109878-72304c02-7549-4eb9-8632-fe4d6ea0dc86.png)


Any chance you had a file open or some process involving some files in the `SoftwareName_Adapter` before you run the bat script? That's the only thing I can think of -- could you try again and see if it works?

**Comment by FraserGreenroyd** [comment] 2022-12-01 16:44
> I can't reproduce on my end:
> 
> ![image](https://user-images.githubusercontent.com/6352844/205109878-72304c02-7549-4eb9-8632-fe4d6ea0dc86.png)

That picture says `SoftwareName_Toolkit.sln` - shouldn't that have been `SE2050_Toolkit.sln`?

**Comment by alelom** [comment] 2022-12-01 16:57
> That picture says `SoftwareName_Toolkit.sln` - shouldn't that have been `SE2050_Toolkit.sln`?

@FraserGreenroyd  Ah sorry that's because after the fist test I tried to reproduce it again by doing some manual changes intentionally, like renaming some files/folder before running the bat -- forgot that when taking the screenshot (I focused on the folder and didn't notice I left out the sln file).

I just tried again, running the bat from scratch, and I get this on my end:

![image](https://user-images.githubusercontent.com/6352844/205113148-c8232b5f-c763-49d7-b60f-fb89fabc3747.png)

**Comment by alelom** [comment] 2022-12-01 17:53
The only explanation I can think of is that the first run of the bat failed because some file/folder in the `SoftwareName_Adapter` folder was opened or non-editable for some reason when the bat was first run; then, subsequent runs failed due to #17.

Raising PR to fix #17, perhaps it will resolve this issue too.

**Comment by michaelhoehn** [comment] 2022-12-01 18:27
> @michaelhoehn are the files inside `SoftwareName_Adapter` renamed to the right name or not?

Yes everything was renamed inside of the adapter folder. 

![image](https://user-images.githubusercontent.com/54593392/205131167-e0223c76-6291-47b3-9007-1adc1e0461d0.png)
![image](https://user-images.githubusercontent.com/54593392/205131202-75dc224d-7e6f-4242-bd7a-2e8766fa947d.png)
![image](https://user-images.githubusercontent.com/54593392/205131245-8d4d2949-793f-4682-a2aa-3bcd267f9836.png)

All CRUD methods were labelled as `_I[methodType].cs` so not sure if that's supposed to be `SE2050_ICreate.cs` for example or if it's fine as is. 
![image](https://user-images.githubusercontent.com/54593392/205131362-a9a8a45f-94c9-4a12-98f5-2ec425e5e066.png)

**Comment by alelom** [comment] 2022-12-02 09:31
> All CRUD methods were labelled as _I[methodType].cs so not sure if that's supposed to be SE2050_ICreate.cs for example or if it's fine as is.

No they must be like this, i.e. `_ICreate.cs`.

**Comment by alelom** [comment] 2022-12-05 19:35
Closed by https://github.com/BHoM/template-repository/pull/18

**Closed as completed by alelom** 2022-12-05 19:35 UTC
Labels: type:bug
